mc_planning Namespace Reference
mc_planning Namespace Reference
Namespaces
internal
linear_control_system
motion_interpolator
Classes
struct CenteredPreviewWindow
Stores parameters related to a preview window.
struct generator
Utility class to generate long and short term trajectories for the CoM.
struct Index
struct LookupTable
Stores precomputed values of a function for fast lookup.
struct Pendulum
State of the inverted pendulum model.
struct PreviewElement
Element returned by CenteredPreviewWindow::iterator providing the current index and allowing to conveniently get the corresponding time.
struct PreviewSteps
Helper class to manage a list of discrete steps and provide efficient sequential lookup of next/previous step.
struct PreviewWindowView
Provides an iterable view on a preview window for convenient safe access to ranges of elements.
struct RangeElementIterator
Virtual iterator for iterating over a range of value and accessing elements of the parent class.
class StateP
class StatePV
class StatePVA
struct Time
struct TimedStep
Functions
template<typename T >
T Max (const T &a, const T &b)
template<typename T >
T Min (const T &a, const T &b)
template<typename T >
int Sign (const T &x)
template<typename T >
T Pow2 (const T &a)
template<typename T >
T polynomial3 (const T &t)
template<typename T >
T dpolynomial3 (const T &t)
template<typename T >
T ddpolynomial3 (const T &t)
template<typename T >
T polynomial5 (const T &t)
template<typename T >
T dpolynomial5 (const T &t)
template<typename T >
T ddpolynomial5 (const T &t)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromRoll (const double &roll)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromPitch (const double &pitch)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromYaw (const double &yaw)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromYrp (const double &y, const double &r, const double &p)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromAngleAxis (const double &angles, const Eigen::Vector3d &axis)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromAngleAxis (const Eigen::Vector3d &omega, const double eps=1.0e-6)
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ rotFromAngleAxis (double e1, double e2, double e3, const double eps=1.0e-6)
Eigen::Vector3d yrpFromRot (const Eigen::Matrix3d &m)
!!! yrpFromRot can't check singularity (p = pi/2)
double yawFromRot (const Eigen::Matrix3d &r)
Eigen::Vector3d omegaFromRotApproximation (const Eigen::Matrix3d &r)
Eigen::Matrix3d mergeTiltWithYaw (const Eigen::Vector3d &Rtez, const Eigen::Matrix3d &R2)
Eigen::Matrix3d mergeRoll1Pitch1WithYaw2 (const Eigen::Matrix3d &R1, const Eigen::Matrix3d &R2)
double Saturation (const double &data, const double ulimit, const double llimit)
double Threshold (const double &data, const double ulimit, const double llimit)
double NormalizedTrapezoidCurve (int n_now, int n_ini, int n_acc, int n_dec, int n_end)
template<class T >
T LowPassFilter (const T &data, T &data_lpf, const double gain)
template<class T >
T HighPassFilter (const T &data, T &data_hpf, const double gain)
template<typename Step >
bool operator< (const TimedStep< Step > &s1, const TimedStep< Step > &s2)
template<typename Step >
std::ostream & operator<< (std::ostream &os, const TimedStep< Step > &step)
Variables
const double epsilonAngle = 1e-16
Function Documentation
ddpolynomial3()
template<typename T > T mc_planning::ddpolynomial3 (const T & t) inline
ddpolynomial5()
template<typename T > T mc_planning::ddpolynomial5 (const T & t) inline
dpolynomial3()
template<typename T > T mc_planning::dpolynomial3 (const T & t) inline
dpolynomial5()
template<typename T > T mc_planning::dpolynomial5 (const T & t) inline
HighPassFilter()
template<class T > T mc_planning::HighPassFilter (const T & data, T & data_hpf, const double gain)
LowPassFilter()
template<class T > T mc_planning::LowPassFilter (const T & data, T & data_lpf, const double gain)
Max()
template<typename T > T mc_planning::Max (const T & a, const T & b) inline
mergeRoll1Pitch1WithYaw2()
Eigen::Matrix3d mc_planning::mergeRoll1Pitch1WithYaw2 (const Eigen::Matrix3d & R1, const Eigen::Matrix3d & R2) inline
References mergeTiltWithYaw(), NormalizedTrapezoidCurve(), Saturation(), and Threshold().
mergeTiltWithYaw()
Eigen::Matrix3d mc_planning::mergeTiltWithYaw (const Eigen::Vector3d & Rtez, const Eigen::Matrix3d & R2) inline
Referenced by mergeRoll1Pitch1WithYaw2().
Min()
template<typename T > T mc_planning::Min (const T & a, const T & b) inline
NormalizedTrapezoidCurve()
double mc_planning::NormalizedTrapezoidCurve (int n_now, int n_ini, int n_acc, int n_dec, int n_end)
Referenced by mergeRoll1Pitch1WithYaw2().
omegaFromRotApproximation()
Eigen::Vector3d mc_planning::omegaFromRotApproximation (const Eigen::Matrix3d & r)
Referenced by rotFromAngleAxis().
operator<()
template<typename Step > bool mc_planning::operator< (const TimedStep< Step > & s1, const TimedStep< Step > & s2)
operator<<()
template<typename Step > std::ostream& mc_planning::operator<< (std::ostream & os, const TimedStep< Step > & step)
References mc_planning::TimedStep< Step >::step().
polynomial3()
template<typename T > T mc_planning::polynomial3 (const T & t) inline
polynomial5()
template<typename T > T mc_planning::polynomial5 (const T & t) inline
Pow2()
template<typename T > T mc_planning::Pow2 (const T & a) inline
rotFromAngleAxis() [1/3]
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromAngleAxis (const double & angles, const Eigen::Vector3d & axis) inline
Referenced by rotFromAngleAxis().
rotFromAngleAxis() [2/3]
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromAngleAxis (const Eigen::Vector3d & omega, const double eps = 1.0e-6) inline
rotFromAngleAxis() [3/3]
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromAngleAxis (double e1, double e2, double e3, const double eps = 1.0e-6) inline
References omegaFromRotApproximation(), rotFromAngleAxis(), yawFromRot(), and yrpFromRot().
rotFromPitch()
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromPitch (const double & pitch) inline
rotFromRoll()
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromRoll (const double & roll) inline
rotFromYaw()
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromYaw (const double & yaw) inline
rotFromYrp()
Eigen::Matrix3d __ATTRIBUTE_ALWAYS_INLINE__ mc_planning::rotFromYrp (const double & y, const double & r, const double & p) inline
Saturation()
double mc_planning::Saturation (const double & data, const double ulimit, const double llimit)
Referenced by mergeRoll1Pitch1WithYaw2().
Sign()
template<typename T > int mc_planning::Sign (const T & x) inline
Threshold()
double mc_planning::Threshold (const double & data, const double ulimit, const double llimit)
Referenced by mergeRoll1Pitch1WithYaw2().
yawFromRot()
double mc_planning::yawFromRot (const Eigen::Matrix3d & r)
Referenced by rotFromAngleAxis().
yrpFromRot()
Eigen::Vector3d mc_planning::yrpFromRot (const Eigen::Matrix3d & m)
!!! yrpFromRot can't check singularity (p = pi/2)
Referenced by rotFromAngleAxis().
Variable Documentation
epsilonAngle
const double mc_planning::epsilonAngle = 1e-16