mc_rtc::log Namespace Reference
mc_rtc::log Namespace Reference
Namespaces
details
Classes
struct callback_is_serializable
Type-traits for callables that returns a serializable type.
struct FlatLog
From an on-disk binary log recorded by mc_rtc, return a flat structure.
struct GetLogType
Helper to build a correspondance between C++ types and enum values.
struct GetLogType< std::vector< double, A > >
struct GetType
struct is_serializable
True if the given type is serializable in the log.
struct LogWriter
For a given type, writes to the log.
Typedefs
using binary_log_callback = std::function< bool(const std::vector< std::string > &, std::vector< FlatLog::record > &, double)>
using copy_callback = std::function< void(mc_rtc::MessagePackBuilder &, const std::vector< std::string > &)>
using binary_log_copy_callback = std::function< bool(const std::vector< std::string > &, std::vector< FlatLog::record > &, double, const copy_callback &, const char *, uint64_t)>
Enumerations
enum LogType {
LogType::None = 0,
LogType::Bool,
LogType::Int8_t,
LogType::Int16_t,
LogType::Int32_t,
LogType::Int64_t,
LogType::Uint8_t,
LogType::Uint16_t,
LogType::Uint32_t,
LogType::Uint64_t,
LogType::Float,
LogType::Double,
LogType::String,
LogType::Vector2d,
LogType::Vector3d,
LogType::Vector6d,
LogType::VectorXd,
LogType::Quaterniond,
LogType::PTransformd,
LogType::ForceVecd,
LogType::MotionVecd,
LogType::VectorDouble
}
Enum representing the type of data being logged.
Functions
bool MC_RTC_UTILS_DLLAPI iterate_binary_log (const std::string &fpath, const binary_log_copy_callback &callback, bool extract, const std::string &time="t")
Iterate over a given binary log data.
bool MC_RTC_UTILS_DLLAPI iterate_binary_log (const std::string &fpath, const binary_log_callback &callback, bool extract, const std::string &time="t")
Iterate over a given binary log data.
const char ** LogTypeNames ()
const char * LogTypeName (LogType t)
IMPL_TYPE_TO_ENUM_MAPPING (bool, Bool)
IMPL_TYPE_TO_ENUM_MAPPING (int8_t, Int8_t)
IMPL_TYPE_TO_ENUM_MAPPING (int16_t, Int16_t)
IMPL_TYPE_TO_ENUM_MAPPING (int32_t, Int32_t)
IMPL_TYPE_TO_ENUM_MAPPING (int64_t, Int64_t)
IMPL_TYPE_TO_ENUM_MAPPING (uint8_t, Uint8_t)
IMPL_TYPE_TO_ENUM_MAPPING (uint16_t, Uint16_t)
IMPL_TYPE_TO_ENUM_MAPPING (uint32_t, Uint32_t)
IMPL_TYPE_TO_ENUM_MAPPING (uint64_t, Uint64_t)
IMPL_TYPE_TO_ENUM_MAPPING (float, Float)
IMPL_TYPE_TO_ENUM_MAPPING (double, Double)
IMPL_TYPE_TO_ENUM_MAPPING (std::string, String)
IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector2d, Vector2d)
IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector3d, Vector3d)
IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector6d, Vector6d)
IMPL_TYPE_TO_ENUM_MAPPING (Eigen::VectorXd, VectorXd)
IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Quaterniond, Quaterniond)
IMPL_TYPE_TO_ENUM_MAPPING (sva::PTransformd, PTransformd)
IMPL_TYPE_TO_ENUM_MAPPING (sva::ForceVecd, ForceVecd)
IMPL_TYPE_TO_ENUM_MAPPING (sva::MotionVecd, MotionVecd)
IMPL_TYPE_TO_ENUM_MAPPING (std::vector< double >, VectorDouble)
IMPL_ENUM_TO_TYPE_MAPPING (bool, Bool)
IMPL_ENUM_TO_TYPE_MAPPING (int8_t, Int8_t)
IMPL_ENUM_TO_TYPE_MAPPING (int16_t, Int16_t)
IMPL_ENUM_TO_TYPE_MAPPING (int32_t, Int32_t)
IMPL_ENUM_TO_TYPE_MAPPING (int64_t, Int64_t)
IMPL_ENUM_TO_TYPE_MAPPING (uint8_t, Uint8_t)
IMPL_ENUM_TO_TYPE_MAPPING (uint16_t, Uint16_t)
IMPL_ENUM_TO_TYPE_MAPPING (uint32_t, Uint32_t)
IMPL_ENUM_TO_TYPE_MAPPING (uint64_t, Uint64_t)
IMPL_ENUM_TO_TYPE_MAPPING (float, Float)
IMPL_ENUM_TO_TYPE_MAPPING (double, Double)
IMPL_ENUM_TO_TYPE_MAPPING (std::string, String)
IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector2d, Vector2d)
IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector3d, Vector3d)
IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector6d, Vector6d)
IMPL_ENUM_TO_TYPE_MAPPING (Eigen::VectorXd, VectorXd)
IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Quaterniond, Quaterniond)
IMPL_ENUM_TO_TYPE_MAPPING (sva::PTransformd, PTransformd)
IMPL_ENUM_TO_TYPE_MAPPING (sva::ForceVecd, ForceVecd)
IMPL_ENUM_TO_TYPE_MAPPING (sva::MotionVecd, MotionVecd)
IMPL_ENUM_TO_TYPE_MAPPING (std::vector< double >, VectorDouble)
template<typename ExceptionT , typename... Args>
void error_and_throw (Args &&... args)
template<typename... Args>
void error (Args &&... args)
template<typename... Args>
void warning (Args &&... args)
template<typename... Args>
void info (Args &&... args)
template<typename... Args>
void success (Args &&... args)
Typedef Documentation
binary_log_callback
using mc_rtc::log::binary_log_callback = typedef std::function<bool(const std::vector<std::string> &, std::vector<FlatLog::record> &, double)>
binary_log_copy_callback
using mc_rtc::log::binary_log_copy_callback = typedef std::function<bool(const std::vector<std::string> &, std::vector<FlatLog::record> &, double, const copy_callback &, const char *, uint64_t)>
copy_callback
using mc_rtc::log::copy_callback = typedef std::function<void(mc_rtc::MessagePackBuilder &, const std::vector<std::string> &)>
Enumeration Type Documentation
LogType
enum mc_rtc::log::LogType strong
Enum representing the type of data being logged.
Enumerator
None
Bool
Int8_t
Int16_t
Int32_t
Int64_t
Uint8_t
Uint16_t
Uint32_t
Uint64_t
Float
Double
String
Vector2d
Vector3d
Vector6d
VectorXd
Quaterniond
PTransformd
ForceVecd
MotionVecd
VectorDouble
Function Documentation
error()
template<typename... Args> void mc_rtc::log::error (Args &&... args)
References mc_rtc::log::details::cerr().
Referenced by mc_planning::PreviewSteps< Eigen::Vector2d >::add(), mc_rtc::Logger::addLogEntry(), mc_observers::ObserverLoader::available_observers(), mc_rbdyn::RobotLoader::get_robot_module(), mc_tasks::force::AdmittanceTask::maxAngularVel(), mc_tasks::force::AdmittanceTask::maxLinearVel(), and mc_rtc::DataStore::remove().
error_and_throw()
template<typename ExceptionT , typename... Args> void mc_rtc::log::error_and_throw (Args &&... args)
References mc_rtc::log::details::cerr().
IMPL_ENUM_TO_TYPE_MAPPING() [1/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (bool , Bool)
IMPL_ENUM_TO_TYPE_MAPPING() [2/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (int8_t , Int8_t)
IMPL_ENUM_TO_TYPE_MAPPING() [3/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (int16_t , Int16_t)
IMPL_ENUM_TO_TYPE_MAPPING() [4/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (int32_t , Int32_t)
IMPL_ENUM_TO_TYPE_MAPPING() [5/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (int64_t , Int64_t)
IMPL_ENUM_TO_TYPE_MAPPING() [6/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (uint8_t , Uint8_t)
IMPL_ENUM_TO_TYPE_MAPPING() [7/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (uint16_t , Uint16_t)
IMPL_ENUM_TO_TYPE_MAPPING() [8/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (uint32_t , Uint32_t)
IMPL_ENUM_TO_TYPE_MAPPING() [9/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (uint64_t , Uint64_t)
IMPL_ENUM_TO_TYPE_MAPPING() [10/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (float , Float)
IMPL_ENUM_TO_TYPE_MAPPING() [11/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (double , Double)
IMPL_ENUM_TO_TYPE_MAPPING() [12/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (std::string , String)
IMPL_ENUM_TO_TYPE_MAPPING() [13/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector2d , Vector2d)
IMPL_ENUM_TO_TYPE_MAPPING() [14/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector3d , Vector3d)
IMPL_ENUM_TO_TYPE_MAPPING() [15/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Vector6d , Vector6d)
IMPL_ENUM_TO_TYPE_MAPPING() [16/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (Eigen::VectorXd , VectorXd)
IMPL_ENUM_TO_TYPE_MAPPING() [17/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (Eigen::Quaterniond , Quaterniond)
IMPL_ENUM_TO_TYPE_MAPPING() [18/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (sva::PTransformd , PTransformd)
IMPL_ENUM_TO_TYPE_MAPPING() [19/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (sva::ForceVecd , ForceVecd)
IMPL_ENUM_TO_TYPE_MAPPING() [20/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (sva::MotionVecd , MotionVecd)
IMPL_ENUM_TO_TYPE_MAPPING() [21/21]
mc_rtc::log::IMPL_ENUM_TO_TYPE_MAPPING (std::vector< double > , VectorDouble)
IMPL_TYPE_TO_ENUM_MAPPING() [1/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (bool , Bool)
IMPL_TYPE_TO_ENUM_MAPPING() [2/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (int8_t , Int8_t)
IMPL_TYPE_TO_ENUM_MAPPING() [3/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (int16_t , Int16_t)
IMPL_TYPE_TO_ENUM_MAPPING() [4/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (int32_t , Int32_t)
IMPL_TYPE_TO_ENUM_MAPPING() [5/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (int64_t , Int64_t)
IMPL_TYPE_TO_ENUM_MAPPING() [6/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (uint8_t , Uint8_t)
IMPL_TYPE_TO_ENUM_MAPPING() [7/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (uint16_t , Uint16_t)
IMPL_TYPE_TO_ENUM_MAPPING() [8/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (uint32_t , Uint32_t)
IMPL_TYPE_TO_ENUM_MAPPING() [9/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (uint64_t , Uint64_t)
IMPL_TYPE_TO_ENUM_MAPPING() [10/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (float , Float)
IMPL_TYPE_TO_ENUM_MAPPING() [11/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (double , Double)
IMPL_TYPE_TO_ENUM_MAPPING() [12/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (std::string , String)
IMPL_TYPE_TO_ENUM_MAPPING() [13/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector2d , Vector2d)
IMPL_TYPE_TO_ENUM_MAPPING() [14/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector3d , Vector3d)
IMPL_TYPE_TO_ENUM_MAPPING() [15/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Vector6d , Vector6d)
IMPL_TYPE_TO_ENUM_MAPPING() [16/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (Eigen::VectorXd , VectorXd)
IMPL_TYPE_TO_ENUM_MAPPING() [17/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (Eigen::Quaterniond , Quaterniond)
IMPL_TYPE_TO_ENUM_MAPPING() [18/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (sva::PTransformd , PTransformd)
IMPL_TYPE_TO_ENUM_MAPPING() [19/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (sva::ForceVecd , ForceVecd)
IMPL_TYPE_TO_ENUM_MAPPING() [20/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (sva::MotionVecd , MotionVecd)
IMPL_TYPE_TO_ENUM_MAPPING() [21/21]
mc_rtc::log::IMPL_TYPE_TO_ENUM_MAPPING (std::vector< double > , VectorDouble)
info()
template<typename... Args> void mc_rtc::log::info (Args &&... args)
Examples:
mc_sample_CoMGeneration.cpp.
References mc_rtc::log::details::info().
Referenced by mc_planning::PreviewSteps< Eigen::Vector2d >::changeFutureSteps(), and mc_rbdyn::RobotLoader::get_robot_module().
iterate_binary_log() [1/2]
bool MC_RTC_UTILS_DLLAPI mc_rtc::log::iterate_binary_log (const std::string & fpath, const binary_log_copy_callback & callback, bool extract, const std::string & time = "t")
Iterate over a given binary log data.
For each entry in the log, this will call the provided callback. The callback has six arguments:
the first are the keys of the entry, note that this is empty if there has been no change since the previous entry
the second is the data corresponding to the keys. The index of a key in the keys vector give the index for the corresponding data. This index may change when keys are updated
the third is the value for the time entry
the fourth is a copy callback that can be used to obtain a copy of the data with provided keys
the fifth is a pointer to the raw buffer data
the sixth is the size of this buffer
If the callback returns false, parsing is aborted
Parameters
fpath Path to the binary log file
callback Called for every entry in the log
extract If true, data is available as their original C++ type, if false, no data is available. Skipping extraction is much faster
time Key used as time source. If that key doesn't exist or if it's not a Double record, the parsing will fail. If this parameter is empty, no extraction is attempted and the third callback parameter is always -1
Returns
True if parsing was sucessful, false otherwise
iterate_binary_log() [2/2]
bool MC_RTC_UTILS_DLLAPI mc_rtc::log::iterate_binary_log (const std::string & fpath, const binary_log_callback & callback, bool extract, const std::string & time = "t")
Iterate over a given binary log data.
This function has the same functionality as its overload but the callback doesn't have to bother with the copy callback.
LogTypeName()
const char* mc_rtc::log::LogTypeName (LogType t) inline
References LogTypeNames().
LogTypeNames()
const char** mc_rtc::log::LogTypeNames () inline
Referenced by LogTypeName().
success()
template<typename... Args> void mc_rtc::log::success (Args &&... args)
Examples:
mc_sample_CoMGeneration.cpp.
References mc_rtc::log::details::success().
warning()
template<typename... Args> void mc_rtc::log::warning (Args &&... args)
References mc_rtc::log::details::cerr().
Referenced by mc_filter::utils::clampAndWarn(), mc_filter::LowPass< sva::MotionVecd >::cutoffPeriod(), and mc_filter::ExponentialMovingAverage< Eigen::Vector3d >::timeConstant().