mc_planning::motion_interpolator::InterpolatorBase< T > Class Template Reference
mc_planning::motion_interpolator::InterpolatorBase< T > Class Template Reference abstract
#include <mc_planning/InterpolatorBase.h>
Public Member Functions
InterpolatorBase (const double &scale_=1.0, const double &eps=0.001, interpolator_type ip_type=NOT_SELECTED)
virtual ~InterpolatorBase ()
const interpolator_type & InterpolatorType (void) const
void clear (void)
unsigned int size (void)
void resize (unsigned int n)
bool empty (void)
std::deque< InterpolatorDataType< T > > & getData (void)
InterpolatorDataType< T > & getData (int n)
InterpolatorDataType< T > & front (void)
InterpolatorDataType< T > & back (void)
virtual bool isFinish (const T &t_)
void pop_front (void)
void pop_back (void)
void push_back (const T &t_, const double &p)
void push_back (const T &t_, const double &p, const double &v)
void push_back (const T &t_, const double &p, const double &v, const double &a)
void push_back (const T &t_, const double &p, bool boundary)
void push_back (const T &t_, const double &p, const double &v, bool boundary)
void push_back (const T &t_, const double &p, const double &v, const double &a, bool boundary)
void push_front (const T &t_, const double &p)
void push_front (const T &t_, const double &p, const double &v)
void push_front (const T &t_, const double &p, const double &v, const double &a)
void push_front (const T &t_, const double &p, bool boundary)
void push_front (const T &t_, const double &p, const double &v, bool boundary)
void push_front (const T &t_, const double &p, const double &v, const double &a, bool boundary)
void set (const int n, const T &t, const double &p)
void set (const int n, const T &t, const double &p, const double &v)
void set (const int n, const T &t, const double &p, const double &v, const double &a)
virtual void set (const int n, const T &t, const double &p, bool boundary)
virtual void set (const int n, const T &t, const double &p, const double &v, bool boundary)
virtual void set (const int n, const T &t, const double &p, const double &v, const double &a, bool boundary)
double getValue (T t_)
void get (T t_, double &p)
void get (T t_, double &p, double &v)
virtual void get (T t_, double &p, double &v, double &a)=0
virtual void update (void)
virtual void update (T t_)
virtual void update (T t_from, T t_to)
Protected Attributes
const double scale
const double eps
std::deque< InterpolatorDataType< T > > data
Constructor & Destructor Documentation
InterpolatorBase()
template<typename T > mc_planning::motion_interpolator::InterpolatorBase< T >::InterpolatorBase (const double & scale_ = 1.0, const double & eps = 0.001, interpolator_type ip_type = NOT_SELECTED)
~InterpolatorBase()
template<typename T > virtual mc_planning::motion_interpolator::InterpolatorBase< T >::~InterpolatorBase () inline virtual
Member Function Documentation
back()
template<typename T > InterpolatorDataType<T>& mc_planning::motion_interpolator::InterpolatorBase< T >::back (void) inline
Referenced by mc_planning::motion_interpolator::CubicSplineBase< T >::get().
clear()
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::clear (void) inline
empty()
template<typename T > bool mc_planning::motion_interpolator::InterpolatorBase< T >::empty (void) inline
Referenced by mc_planning::motion_interpolator::CubicSplineBase< T >::get().
front()
template<typename T > InterpolatorDataType<T>& mc_planning::motion_interpolator::InterpolatorBase< T >::front (void) inline
Referenced by mc_planning::motion_interpolator::CubicSplineBase< T >::get().
get() [1/3]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::get (T t_, double & p)
get() [2/3]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::get (T t_, double & p, double & v)
get() [3/3]
template<typename T > virtual void mc_planning::motion_interpolator::InterpolatorBase< T >::get (T t_, double & p, double & v, double & a) pure virtual
Implemented in mc_planning::motion_interpolator::CubicSplineBase< T >.
getData() [1/2]
template<typename T > std::deque<InterpolatorDataType<T> >& mc_planning::motion_interpolator::InterpolatorBase< T >::getData (void) inline
getData() [2/2]
template<typename T > InterpolatorDataType<T>& mc_planning::motion_interpolator::InterpolatorBase< T >::getData (int n) inline
getValue()
template<typename T > double mc_planning::motion_interpolator::InterpolatorBase< T >::getValue (T t_)
InterpolatorType()
template<typename T > const interpolator_type& mc_planning::motion_interpolator::InterpolatorBase< T >::InterpolatorType (void) const inline
isFinish()
template<typename T > virtual bool mc_planning::motion_interpolator::InterpolatorBase< T >::isFinish (const T & t_) inline virtual
pop_back()
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::pop_back (void) inline
pop_front()
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::pop_front (void) inline
push_back() [1/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p) inline
push_back() [2/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p, const double & v) inline
push_back() [3/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p, const double & v, const double & a) inline
push_back() [4/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p, bool boundary) inline
push_back() [5/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p, const double & v, bool boundary) inline
push_back() [6/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_back (const T & t_, const double & p, const double & v, const double & a, bool boundary) inline
push_front() [1/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p) inline
push_front() [2/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p, const double & v) inline
push_front() [3/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p, const double & v, const double & a) inline
push_front() [4/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p, bool boundary) inline
push_front() [5/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p, const double & v, bool boundary) inline
push_front() [6/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::push_front (const T & t_, const double & p, const double & v, const double & a, bool boundary) inline
References mc_planning::motion_interpolator::InterpolatorDataType< T >::boundary, and mc_planning::motion_interpolator::InterpolatorDataType< T >::t.
resize()
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::resize (unsigned int n) inline
Referenced by mc_planning::motion_interpolator::ClampedCubicSpline< T >::setSplineCoeff().
set() [1/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p)
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
set() [2/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p, const double & v)
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
set() [3/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p, const double & v, const double & a)
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
set() [4/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p, bool boundary) virtual
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
set() [5/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p, const double & v, bool boundary) virtual
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
set() [6/6]
template<typename T > void mc_planning::motion_interpolator::InterpolatorBase< T >::set (const int n, const T & t, const double & p, const double & v, const double & a, bool boundary) virtual
References mc_planning::motion_interpolator::InterpolatorBase< T >::data.
size()
template<typename T > unsigned int mc_planning::motion_interpolator::InterpolatorBase< T >::size (void) inline
Referenced by mc_planning::motion_interpolator::CubicSplineBase< T >::get().
update() [1/3]
template<typename T > virtual void mc_planning::motion_interpolator::InterpolatorBase< T >::update (void) inline virtual
Reimplemented in mc_planning::motion_interpolator::CubicSplineBase< T >.
update() [2/3]
template<typename T > virtual void mc_planning::motion_interpolator::InterpolatorBase< T >::update (T t_) inline virtual
Reimplemented in mc_planning::motion_interpolator::CubicSplineBase< T >.
update() [3/3]
template<typename T > virtual void mc_planning::motion_interpolator::InterpolatorBase< T >::update (T t_from, T t_to) inline virtual
Reimplemented in mc_planning::motion_interpolator::CubicSplineBase< T >.
Member Data Documentation
data
template<typename T > std::deque<InterpolatorDataType<T> > mc_planning::motion_interpolator::InterpolatorBase< T >::data protected
Referenced by mc_planning::motion_interpolator::InterpolatorBase< T >::set().
eps
template<typename T > const double mc_planning::motion_interpolator::InterpolatorBase< T >::eps protected
scale
template<typename T > const double mc_planning::motion_interpolator::InterpolatorBase< T >::scale protected