mc_planning::TimedStep< Step > Struct Template Reference
mc_planning::TimedStep< Step > Struct Template Reference
#include <mc_planning/PreviewSteps.h>
Public Member Functions
TimedStep (double t, const Step &step) noexcept
TimedStep () noexcept
const double & t () const noexcept
double & t () noexcept
const Step & step () const noexcept
Step & step () noexcept
bool operator< (const TimedStep &t) const noexcept
bool operator<= (const TimedStep &t) const noexcept
void operator+ (const TimedStep &t) noexcept
TimedStep & operator+= (const TimedStep &rhs) noexcept
void operator- (const TimedStep &t) noexcept
TimedStep & operator-= (const TimedStep &rhs) noexcept
Protected Attributes
double t_ = 0
Step step_
Constructor & Destructor Documentation
TimedStep() [1/2]
template<typename Step> mc_planning::TimedStep< Step >::TimedStep (double t, const Step & step) inline noexcept
TimedStep() [2/2]
template<typename Step> mc_planning::TimedStep< Step >::TimedStep () inline noexcept
Member Function Documentation
operator+()
template<typename Step> void mc_planning::TimedStep< Step >::operator+ (const TimedStep< Step > & t) inline noexcept
operator+=()
template<typename Step> TimedStep& mc_planning::TimedStep< Step >::operator+= (const TimedStep< Step > & rhs) inline noexcept
operator-()
template<typename Step> void mc_planning::TimedStep< Step >::operator- (const TimedStep< Step > & t) inline noexcept
operator-=()
template<typename Step> TimedStep& mc_planning::TimedStep< Step >::operator-= (const TimedStep< Step > & rhs) inline noexcept
operator<()
template<typename Step> bool mc_planning::TimedStep< Step >::operator< (const TimedStep< Step > & t) const inline noexcept
operator<=()
template<typename Step> bool mc_planning::TimedStep< Step >::operator<= (const TimedStep< Step > & t) const inline noexcept
step() [1/2]
template<typename Step> const Step& mc_planning::TimedStep< Step >::step () const inline noexcept
Referenced by mc_planning::PreviewSteps< Eigen::Vector2d >::addRelative(), mc_planning::PreviewSteps< Eigen::Vector2d >::changeFutureSteps(), mc_planning::PreviewSteps< Eigen::Vector2d >::deleteAfter(), mc_planning::PreviewSteps< Eigen::Vector2d >::next(), mc_planning::operator<<(), and mc_planning::PreviewSteps< Eigen::Vector2d >::previous().
step() [2/2]
template<typename Step> Step& mc_planning::TimedStep< Step >::step () inline noexcept
t() [1/2]
template<typename Step> const double& mc_planning::TimedStep< Step >::t () const inline noexcept
Referenced by mc_planning::PreviewSteps< Eigen::Vector2d >::add(), mc_planning::PreviewSteps< Eigen::Vector2d >::deleteAfter(), mc_planning::PreviewSteps< Eigen::Vector2d >::next(), mc_planning::PreviewSteps< Eigen::Vector2d >::nextWindow(), mc_planning::TimedStep< Eigen::Vector2d >::operator+(), mc_planning::TimedStep< Eigen::Vector2d >::operator-(), mc_planning::TimedStep< Eigen::Vector2d >::operator<(), mc_planning::TimedStep< Eigen::Vector2d >::operator<=(), mc_planning::PreviewSteps< Eigen::Vector2d >::previous(), and mc_planning::PreviewSteps< Eigen::Vector2d >::update().
t() [2/2]
template<typename Step> double& mc_planning::TimedStep< Step >::t () inline noexcept
Member Data Documentation
step_
template<typename Step> Step mc_planning::TimedStep< Step >::step_ protected
Referenced by mc_planning::TimedStep< Eigen::Vector2d >::operator+(), mc_planning::TimedStep< Eigen::Vector2d >::operator+=(), mc_planning::TimedStep< Eigen::Vector2d >::operator-(), mc_planning::TimedStep< Eigen::Vector2d >::operator-=(), and mc_planning::TimedStep< Eigen::Vector2d >::step().
t_
template<typename Step> double mc_planning::TimedStep< Step >::t_ = 0 protected
Referenced by mc_planning::TimedStep< Eigen::Vector2d >::operator+(), mc_planning::TimedStep< Eigen::Vector2d >::operator+=(), mc_planning::TimedStep< Eigen::Vector2d >::operator-(), mc_planning::TimedStep< Eigen::Vector2d >::operator-=(), mc_planning::TimedStep< Eigen::Vector2d >::operator<(), mc_planning::TimedStep< Eigen::Vector2d >::operator<=(), and mc_planning::TimedStep< Eigen::Vector2d >::t().