mc_planning::CenteredPreviewWindow Struct Reference
mc_planning::CenteredPreviewWindow Struct Reference
Iterable range over a preview window with convenience time-management.
#include <mc_planning/PreviewWindow.h>
Public Types
using iterator = RangeElementIterator< PreviewElement, CenteredPreviewWindow, false >
using const_iterator = RangeElementIterator< PreviewElement, CenteredPreviewWindow, true >
Public Member Functions
CenteredPreviewWindow (double halfTime, double dt, const double startTime=0.) noexcept
Constructs a window of duration 2*halfTime with the current element at the center.
void startAtTime (double t) noexcept
Start the preview window at the provided time.
void startAtIndex (unsigned index) noexcept
Start the preview window at the provided index.
double startTime () const noexcept
Time at the start of the preview window.
unsigned startIndex () const noexcept
Index of the start of the preview window.
double currentTime () const noexcept
Time at the center of the preview window.
unsigned currentIndex () const noexcept
Index of the center of the preview window.
double endTime () const noexcept
Index of the end of the preview window.
unsigned endIndex () const noexcept
Index of the end of the preview window.
unsigned indexFromTime (double t) const noexcept
Converts between time and index.
double timeFromIndex (unsigned index) const noexcept
Converts between index and time.
double dt () const noexcept
Timestep.
unsigned halfSize () const noexcept
Number of future or past elements.
double halfDuration () const noexcept
Duration corresponding to halfSize()
unsigned size () const noexcept
Full size of the preview window.
double duration () const noexcept
Full duration of the preview window.
Range iterators for computing index/time along the preview window
iterator begin () noexcept
iterator end () noexcept
const_iterator cbegin () noexcept
const_iterator cend () noexcept
CenteredPreviewWindow iterateFromTime (double startTime) const noexcept
Iterate over a copy of the preview window.
CenteredPreviewWindow iterateFromIndex (unsigned startIndex) const noexcept
Iterate over a copy of the preview window.
CenteredPreviewWindow copy () const noexcept
Generate a copy of the current preview window.
Protected Attributes
unsigned halfSize_ = 0
Number of future or past element.
unsigned fullSize_ = 0
2*halfSize_+1
unsigned start_ = 0
Index at which the window starts.
double dt_ = 0.005
Timestep.
Detailed Description
Iterable range over a preview window with convenience time-management.
The preview window is centered around the current element \([-N, current, N] \) where N is the number of elements before and after the current value. The full preview window is of size 2*N+1. The timestep is used to compute correspondances between discrete index of values stored in an (external) container and time.
Additionally, this class provides iterable ranges over the preview window. For example:
// Create an iterable preview window range with a window of time `2*1.6`,
// timestep of 0.005 and starting at time `t=0.5`
CenteredPreviewWindow window(1.6, 0.005, 0.5);
mc_rtc::log::info("Start time:   {:.3f}, index: {}\n"
                  "End time:     {:.3f}, index: {}\n"
                  "Current time: {:.3f}, index: {}",
                  window.startTime(),    window.startIndex(),
                  window.endTime(),      window.endIndex(),
                  window.currentTime(),  window.currentIndex());
// Iterate over the preview window using a RangeElementIterator
for(const auto & w : window)
{
  mc_rtc::log::info("Preview element with index: {}, time: {:.3f}", w.index(), w.time());
  // Example: Access some external container using the index
  // auto value = container[w.index()];
}
// Iterate over a copy of the preview window (cheap copy) starting at a specific time using a RangeElementIterator
for(const auto & w : window.iterateFromTime(1.6))
{
  mc_rtc::log::info(
    "Preview element with global index: {}, time: {:.3f}\n"
    "                     local  index: {}, time: {:.3f}\n"
  , w.index(), w.time()
  , w.localIndex(), w.localTime()
  );
  // Global time starts at 1.6s, while local time is between [0, window.duration()]
}
See also
For practical use, see:
mc_planning::generator
mc_planning::linear_control_system::LinearTimeVariantInvertedPendulum
Member Typedef Documentation
const_iterator
using mc_planning::CenteredPreviewWindow::const_iterator = RangeElementIterator<PreviewElement, CenteredPreviewWindow, true>
iterator
using mc_planning::CenteredPreviewWindow::iterator = RangeElementIterator<PreviewElement, CenteredPreviewWindow, false>
Constructor & Destructor Documentation
CenteredPreviewWindow()
mc_planning::CenteredPreviewWindow::CenteredPreviewWindow (double halfTime, double dt, const double startTime = 0.) inline explicit noexcept
Constructs a window of duration 2*halfTime with the current element at the center.
Parameters
halfTime Half-duration of the window
dt Timesep
startTime Time at which the window starts
Member Function Documentation
begin()
iterator mc_planning::CenteredPreviewWindow::begin () inline noexcept
cbegin()
const_iterator mc_planning::CenteredPreviewWindow::cbegin () inline noexcept
cend()
const_iterator mc_planning::CenteredPreviewWindow::cend () inline noexcept
copy()
CenteredPreviewWindow mc_planning::CenteredPreviewWindow::copy () const inline noexcept
Generate a copy of the current preview window.
currentIndex()
unsigned mc_planning::CenteredPreviewWindow::currentIndex () const inline noexcept
Index of the center of the preview window.
currentTime()
double mc_planning::CenteredPreviewWindow::currentTime () const inline noexcept
Time at the center of the preview window.
dt()
double mc_planning::CenteredPreviewWindow::dt () const inline noexcept
Timestep.
duration()
double mc_planning::CenteredPreviewWindow::duration () const inline noexcept
Full duration of the preview window.
end()
iterator mc_planning::CenteredPreviewWindow::end () inline noexcept
endIndex()
unsigned mc_planning::CenteredPreviewWindow::endIndex () const inline noexcept
Index of the end of the preview window.
endTime()
double mc_planning::CenteredPreviewWindow::endTime () const inline noexcept
Index of the end of the preview window.
halfDuration()
double mc_planning::CenteredPreviewWindow::halfDuration () const inline noexcept
Duration corresponding to halfSize()
halfSize()
unsigned mc_planning::CenteredPreviewWindow::halfSize () const inline noexcept
Number of future or past elements.
The preview window is of size 2*halfSize_+1
indexFromTime()
unsigned mc_planning::CenteredPreviewWindow::indexFromTime (double t) const inline noexcept
Converts between time and index.
Parameters
t Time
Returns
Index corresponding to the provided time
iterateFromIndex()
CenteredPreviewWindow mc_planning::CenteredPreviewWindow::iterateFromIndex (unsigned startIndex) const inline noexcept
Iterate over a copy of the preview window.
The preview window constains only the window parameters and is cheap to copy.
Parameters
startIndex Index from which to iterate
Returns
A copy of the preview window starting at index startIndex
References startAtIndex().
iterateFromTime()
CenteredPreviewWindow mc_planning::CenteredPreviewWindow::iterateFromTime (double startTime) const inline noexcept
Iterate over a copy of the preview window.
The preview window constains only the window parameters and is cheap to copy.
Parameters
startTime Time from which to iterate
Returns
A copy of the preview window starting at time startTime
References startAtTime().
size()
unsigned mc_planning::CenteredPreviewWindow::size (void) const inline noexcept
Full size of the preview window.
startAtIndex()
void mc_planning::CenteredPreviewWindow::startAtIndex (unsigned index) inline noexcept
Start the preview window at the provided index.
Referenced by iterateFromIndex().
startAtTime()
void mc_planning::CenteredPreviewWindow::startAtTime (double t) inline noexcept
Start the preview window at the provided time.
Parameters
t Time at which the window starts
Referenced by iterateFromTime().
startIndex()
unsigned mc_planning::CenteredPreviewWindow::startIndex () const inline noexcept
Index of the start of the preview window.
startTime()
double mc_planning::CenteredPreviewWindow::startTime () const inline noexcept
Time at the start of the preview window.
timeFromIndex()
double mc_planning::CenteredPreviewWindow::timeFromIndex (unsigned index) const inline noexcept
Converts between index and time.
Parameters
index Index
Returns
Time corresponding to the provided index
Member Data Documentation
dt_
double mc_planning::CenteredPreviewWindow::dt_ = 0.005 protected
Timestep.
fullSize_
unsigned mc_planning::CenteredPreviewWindow::fullSize_ = 0 protected
2*halfSize_+1
halfSize_
unsigned mc_planning::CenteredPreviewWindow::halfSize_ = 0 protected
Number of future or past element.
start_
unsigned mc_planning::CenteredPreviewWindow::start_ = 0 protected
Index at which the window starts.